<?php
/**
 *  DO NOT EDIT THIS FILE!
 *
 *  Save this file as iwa_config.php before editing. 
 */
global $iwa_root;

/**
 *  Your document root. For example, if your site is hosted on localhost/iwa,
 *  your document root should be '/iwa/'. If it is hosted on iwa.dev, it should
 *  just be '/'.
 */
$iwa_root = "/";

/**
 *  Function for getting the site root, if you dislike globals.
 */
function site_root() {
    global $iwa_root;
    return $iwa_root;
}
